name: ytvsttk
description: The voting app to settle Youtube Vs. Tiktok

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: fonts/BalsamiqSans-Bold.ttf
          weight: 900
        - asset: fonts/BalsamiqSans-BoldItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/BalsamiqSans-Italic.ttf
          style: italic
        - asset: fonts/BalsamiqSans-Regular.ttf

  uses-material-design: true